### ISSUE TITLE
[EPIC] Improve the unit test coverage

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1102]
At present, the unit test coverage is around 25%. It's scary to refactor or change existing code while adding the new feature.
Need to improve the code coverage for essential modules like
- core - https://github.com/fabric8io/fabric8-maven-plugin/tree/master/core
- enricher - https://github.com/fabric8io/fabric8-maven-plugin/tree/master/enricher
- generator - https://github.com/fabric8io/fabric8-maven-plugin/tree/master/generator
- mojo - https://github.com/fabric8io/fabric8-maven-plugin/tree/master/plugin

Tasks:
- [x] Identify the classes to test 
- [x] Prepare the test plan
- [ ] Implement the unit tests
