### ISSUE TITLE
[EPIC] Add regression/functional tests for booster projects

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1103]
At present, there is no regression test exist to verify the deployment of booster/starter applications [1] [2] on Kubernetes and OpenShift environment.
Any release or PR can go through a regression test for plugin project that can make sure application deployment is functioning well. 

**Applications to deploy:**
[1] [VertX](https://github.com/openshiftio-vertx-boosters)
[2] [Springboot](https://github.com/snowdrop)

The broader idea is to have regression test suit that can run on PR submission of [plugin](https://github.com/fabric8io/fabric8-maven-plugin), [kubernetes-client](https://github.com/fabric8io/kubernetes-client) and [kubernetes-model](https://github.com/fabric8io/kubernetes-model) projects to test the deployment of booster applications[1][2] 

**Tasks:**
- [x] Identify the testing framework/tools for to implement the test by implementing simple deployment test
- [x] Prepare test cases
- [x] Implements tests
- [x] Scripts to prepare test environment
- [x] CI/CD integration if applicable 
- [x] Update the documentation if applicable

**Comment by hrishin** [comment]
Evaluate https://github.com/fabric8io/fabric8/tree/master/components/kubernetes-assertions for assertions

**Comment by hrishin** [comment]
To run these regression tests, first, we need to bring test environment in place
1. Running OpenShift (minishift) environment or Mock server (as per meeting discussion) 
2. Script to bring this[1] environment on CI/CD instances
To begin with the basic implementation we would like to run the test against minishift then eventually substitute minishift with good mocking sever implementation.

**Comment by hrishin** [comment]
With the first run of regression tests, we need to fix the following issues
- [ ] Test behavior on Travis environment is intermittent. Sometimes tests are running well, sometimes tests are getting failed with some error in f8-m-p like #1133 
- [ ] On an average CI job for test taking more than 20 minutes
- [ ] Fixed the build issue for OpenShift v3.7 #1130 as its affecting overall test behavior and performance as well

**Comment by piyush1594** [comment]
@hrishin Can we close this now

**Comment by piyush1594** [comment]
As #1198 is closed by #1199 and #1130 is also closed, I am merging this.
