### ISSUE TITLE
Tentative Roadmap

### ISSUE THREAD

**Issue by piyush1594** [fabric8io/fabric8-maven-plugin#1212]
Tentative Roadmap for FMP. Listed here the issues which can be important from OSIO Prospective

- [ ] Fix Performance Issue #1208 
- [ ] Allow generating service without yaml #1209 
- [ ] Add support matrix table #1207 
- [ ] Fix CI Setup of FMP #1198 
- [ ] Add regression tests #1103 
- [ ] Fix Regression test Issues #135
- [ ] Unable to build multimodule project FMP 3.5.34 onwards #1184 
- [ ] Add regression test for multimodule project #1197  
- [ ] Unable to deploy using FMP 3.5.34 onwards on Openshift 3.5 #1183
- [ ] Support Spring boot 2 #1206 
- [ ] F8 -springboot - health check ignores context path #1120 
- [ ] Minor Changes to ImageTrigger Generation #1177 
- [ ] Improve fabric8:import #1091 
- [ ] fabric8:import #1081 
- [ ] Support for Multi containers in Resource fragments #968 
- [ ] Upgrade to 3.X of the model #1067 
- [ ] Exception in Reconnect Errors while watching build in fmps #1159 
- [ ] Deployment does not complete with Opesnhift 3.7.1 #1168 
- [ ] Specifyinf Dockerfile is broken #1097 
- [ ] Init containers not working with Deployment Config #1114 
- [ ] Plugin should support resource type #963 
- [ ] Revert default image name back to latest #1093 
- [ ] Istio Support #1164 
- [ ] Add support for Istio via enricher #1119 
- [ ] Add unit test coverage #1102 
- [ ] Unit test coverage for Enricher, Generator, Plugin #1106, #1105 , #1104 
- [ ] Fix startup script for windows #1100

**Comment by rhuss** [comment]
Coming back to this roadmap, is this still the plan ? (There seems to be quite of a silence since its started). 

Maybe we can take a step back and reconsider the priorisation ? I.e. it would be awesome if could consolidate on this plugin and harden it for its current functionality.

On first glance, I see the following open issues and task:

- [ ] Remove unused goals #1313 
- [ ] Remove dependency on https://github.com/fabric8io/fabric8
- [ ] Extract Enricher and Generator to fabric8-build
- [ ] Fix `watch` Mojo #1069 
- [ ] Keep nodePort stable on deredployment #894 

Wrt to the release management, what would be the next major release ? Is it 4.0 ?

**Comment by rhuss** [comment]
@oskutka @rohanKanojia @piyush1594 Can we please discuss the roadmap how we want to move on ? Happy to schedule a call, too.

**Comment by rohanKanojia** [comment]
@rhuss : Yes, We would love to schedule a call with you guys in order to discuss the roadmap for fmp, refactoring fmp to fabric8-build, dmp integration etc

cc @oskutka

**Comment by rhuss** [comment]
I update 2 boards in https://github.com/fabric8io/fabric8-maven-plugin/projects to reflect the idea I would have for a roadmap (including concrete tasks):

* fmp 4.x for a consolidation phase, touching down to the required features and cleaning & stabilizing fmp
* fmp 5.x for moving out the core functionality to be usable by other projects

I would leave fmp 3.x as it is now, branching off from the latest release for the most urgent bugs.
